meta_product_name: "Louise Hill Portfolio"
meta_title: "Louise Hill - Digital Product Designer and Strategist"
meta_description: "Louise Hill is an experienced digital product designer and strategist, specialising in UX, UI and product strategy"
meta_image: "cover.png" # should exist in `app/assets/images/`